"""initial migration

Revision ID: 2b572126686e
Revises: None
Create Date: 2016-05-16 20:36:32.320000

"""

# revision identifiers, used by Alembic.
revision = '2b572126686e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
