"""add some fake words

Revision ID: 4c340507f5f5
Revises: 2b572126686e
Create Date: 2016-05-16 20:41:26.279000

"""

# revision identifiers, used by Alembic.
revision = '4c340507f5f5'
down_revision = '2b572126686e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
