"""initial migration

Revision ID: f445ba4b6cc
Revises: None
Create Date: 2016-05-16 19:51:53.987000

"""

# revision identifiers, used by Alembic.
revision = 'f445ba4b6cc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
